"""
Auth Module.

Generated by: aq add module auth

Includes four sklearn ML pipelines registered via @model:
  - LoginRiskClassifier
  - AnomalyDetector
  - BruteForceDetector
  - UserBehaviorClassifier
"""

from .controllers import *
from .services import *
from .faults import *
from .tasks import *
from .test_routes import *
from .pipelines import *   # noqa: F401 – registers @model pipelines

__module_name__ = "auth"
__version__ = "0.1.0"