"""
Module Manifest: auth
Generated by: aq add module auth

This file is the single source of truth for the auth module.
It controls:

Component Registration:
  - controllers, services, models, middleware, guards, pipes, interceptors

Module-Level Settings (override workspace defaults for this module only):
  - sessions: Module-specific session policies
  - cache: Module-specific cache configuration
  - auth: Module-specific authentication settings
  - database: Module-specific database/ORM configuration
  - templates: Module-specific template directories
  - faults: Module-specific error handling and fault domains

Cross-Module Dependencies:
  - imports: Modules this module depends on
  - exports: Services/components visible to other modules
"""

from aquilia import AppManifest
from aquilia.manifest import (
    BackgroundTaskConfig,
    FaultHandlingConfig,
    MiddlewareConfig,
    SessionConfig,
    DatabaseConfig,
    TemplateConfig,
)


manifest = AppManifest(
    # ── Identity ──────────────────────────────────────────────────────
    name="auth",
    version="0.1.0",
    description="Auth module",
    author="",
    tags=["auth"],

    # ── Components ────────────────────────────────────────────────────
    controllers=[
        "modules.auth.controllers:AuthController",
    ],
    services=[
        "modules.auth.services:AuthService",
    ],
    models=[
        "modules.auth.models:Auth",
    ],
    middleware=[],
    guards=[],
    pipes=[],
    interceptors=[],

    # ── Routing ───────────────────────────────────────────────────────
    route_prefix="/auth",
    base_path="modules.auth",

    # ── Cross-Module Dependencies ─────────────────────
    imports=[],
    exports=[
        # Services/components visible to modules that import this module.
        # "modules.auth.services:AuthService",
    ],

    # ── Error Handling (module-level) ─────────────────────────────────
    faults=FaultHandlingConfig(
        default_domain="AUTH",
        strategy="propagate",
    ),

    # ── Background Tasks ─────────────────────────────────────────────
    background_tasks=BackgroundTaskConfig(
        tasks=[
            "modules.auth.tasks:cleanup_expired_sessions",
            "modules.auth.tasks:record_login_attempt",
            "modules.auth.tasks:check_account_lockout",
        ],
        default_queue="auth",
        auto_discover=True,
    ),

    # ── Database (module-level override) ──────────────────────────────
    # Uncomment to use a separate database for this module:
    # database=DatabaseConfig(
    #     url="sqlite:///modules/auth/db.sqlite3",
    #     scan_dirs=["modules/auth/models"],
    #     auto_create=True,
    # ),

    # ── Sessions (module-level override) ──────────────────────────────
    # Uncomment to define module-specific session policies:
    # sessions=[
    #     SessionConfig(
    #         name="auth_session",
    #         ttl=timedelta(hours=1),
    #         store="memory",
    #     ),
    # ],

    # ── Templates (module-level) ──────────────────────────────────────
    # Uncomment to add module-specific template directories:
    # templates=TemplateConfig(
    #     search_paths=["modules/auth/templates"],
    # ),

    # ── Auto-Discovery ────────────────────────────────────────────────
    auto_discover=True,
    discover_patterns=["controllers", "services", "models", "middleware", "guards"],
)


__all__ = ["manifest"]