"""
Module Manifest: authentication
Generated by: aq add module authentication

This file is the single source of truth for the authentication module.
It controls:

Component Registration:
  - controllers, services, models, middleware, guards, pipes, interceptors

Module-Level Settings (override workspace defaults for this module only):
  - sessions: Module-specific session policies
  - cache: Module-specific cache configuration
  - auth: Module-specific authentication settings
  - database: Module-specific database/ORM configuration
  - templates: Module-specific template directories
  - faults: Module-specific error handling and fault domains

Cross-Module Dependencies:
  - imports: Modules this module depends on
  - exports: Services/components visible to other modules
"""

from aquilia import AppManifest
from aquilia.manifest import (
    FaultHandlingConfig,
    MiddlewareConfig,
    SessionConfig,
    DatabaseConfig,
    TemplateConfig,
)


manifest = AppManifest(
    # ── Identity ──────────────────────────────────────────────────────
    name="authentication",
    version="0.1.0",
    description="Authentication module",
    author="",
    tags=["authentication"],

    # ── Components ────────────────────────────────────────────────────
    controllers=[
        "modules.authentication.controllers:AuthenticationController",
    ],
    services=[
        "modules.authentication.services:AuthenticationService",
    ],
    models=[
        "modules.authentication.models:Authentication",
    ],
    middleware=[],
    guards=[],
    pipes=[],
    interceptors=[],

    # ── Routing ───────────────────────────────────────────────────────
    route_prefix="/authentication",
    base_path="modules.authentication",

    # ── Cross-Module Dependencies (NestJS-style) ─────────────────────
    imports=[],
    exports=[
        # Services/components visible to modules that import this module.
        # "modules.authentication.services:AuthenticationService",
    ],

    # ── Error Handling (module-level) ─────────────────────────────────
    faults=FaultHandlingConfig(
        default_domain="AUTHENTICATION",
        strategy="propagate",
    ),

    # ── Database (module-level override) ──────────────────────────────
    # Uncomment to use a separate database for this module:
    # database=DatabaseConfig(
    #     url="sqlite:///modules/authentication/db.sqlite3",
    #     scan_dirs=["modules/authentication/models"],
    #     auto_create=True,
    # ),

    # ── Sessions (module-level override) ──────────────────────────────
    # Uncomment to define module-specific session policies:
    # sessions=[
    #     SessionConfig(
    #         name="authentication_session",
    #         ttl=timedelta(hours=1),
    #         store="memory",
    #     ),
    # ],

    # ── Templates (module-level) ──────────────────────────────────────
    # Uncomment to add module-specific template directories:
    # templates=TemplateConfig(
    #     search_paths=["modules/authentication/templates"],
    # ),

    # ── Auto-Discovery ────────────────────────────────────────────────
    auto_discover=True,
    discover_patterns=["controllers", "services", "models", "middleware", "guards"],
)


__all__ = ["manifest"]