"""
Aquilia ASGI Runtime — rest_api_contract
========================================

Auto-generated by ``aq run``.  DO NOT EDIT — regenerated on every launch.

Timestamp : 2026-07-25 00:12:48
Workspace : rest_api_contract
Mode      : dev
Modules   : 1 (rest)

Usage
-----
Development  : aq run
Production   : uvicorn runtime.app:app --host 0.0.0.0 --port 8000 --workers 4
Gunicorn     : gunicorn runtime.app:app -k uvicorn.workers.UvicornWorker -w 4
Hypercorn    : hypercorn runtime.app:app --bind 0.0.0.0:8000
Docker       : CMD ["uvicorn", "runtime.app:app", "--host", "0.0.0.0"]
"""

from __future__ import annotations

from pathlib import Path

from aquilia.runtime import AquiliaRuntime

# ────────────────────────────────────────────────────────────────────────
# Bootstrap via AquiliaRuntime
# ────────────────────────────────────────────────────────────────────────
_WORKSPACE_ROOT = Path(__file__).resolve().parent.parent

runtime = AquiliaRuntime.from_workspace(
    workspace_root=_WORKSPACE_ROOT,
    mode="dev",
)

# ────────────────────────────────────────────────────────────────────────
# ASGI application export
# ────────────────────────────────────────────────────────────────────────
server = runtime.server
app = runtime.app
