"""
Aquilia Workspace Configuration - Production Grade
Generated by: aq init workspace rest_api_contract

Single-file workspace configuration.
Everything — structure, modules, integrations, and operational
settings (server, auth, DB) — lives in this one file.

- Type-safe with full IDE support
- Version-controlled and shared across team
- Observable via introspection
- Environment layering via AquilaConfig subclasses

Override order: BaseEnv → <AQ_ENV>Env → environment variables
"""

from aquilia import AquilaConfig, Env, Module, Secret, Workspace
from aquilia.integrations import (
    CacheIntegration,
    DatabaseIntegration,
    DiIntegration,
    FaultHandlingIntegration,
    MiddlewareChain,
    PatternsIntegration,
    RegistryIntegration,
    RoutingIntegration,
    SpeculaIntegration,
    StaticFilesIntegration,
    TemplatesIntegration,
)

# ── Environment Configuration ────────────────────────────────────
# Operational settings (server, auth, DB, mail) as Python classes.
# Activate: AQ_ENV=dev (default) | AQ_ENV=prod

class BaseEnv(AquilaConfig):
    """Shared defaults — every environment inherits these."""
    env = "dev"

    class server(AquilaConfig.Server):
        host    = "127.0.0.1"
        port    = 8000
        workers = 1
        reload  = False

        # ── Timeouts ───────────────────────────────────────────
        # timeout_keep_alive = 5        # seconds to keep idle connections open
        # timeout_worker_healthcheck = 30  # seconds before worker considered unresponsive
        # timeout_graceful_shutdown = 30 # seconds to wait on shutdown

        # ── Limits ─────────────────────────────────────────────
        # backlog            = 2048      # TCP connection backlog
        # limit_concurrency  = None      # max concurrent connections
        # limit_max_requests = None      # restart worker after N requests

        # ── Proxy / Headers ───────────────────────────────────
        # proxy_headers      = True      # trust X-Forwarded-* headers
        # forwarded_allow_ips = "*"      # IPs allowed to set proxy headers
        # root_path          = ""        # ASGI root_path for reverse proxies

        # ── WebSocket ─────────────────────────────────────────
        # ws_max_size        = 16_777_216  # max WebSocket message (16 MiB)
        # ws_ping_interval   = 20.0        # ping every N seconds
        # ws_ping_timeout    = 20.0        # close if pong not received

        # ── TLS / SSL ─────────────────────────────────────────
        # ssl_certfile       = "/etc/certs/cert.pem"
        # ssl_keyfile        = "/etc/certs/key.pem"
        # ssl_ca_certs       = None

        # ── Protocol Implementation ───────────────────────────
        # http = "auto"        # "auto" | "h11" | "httptools"
        # ws   = "auto"        # "auto" | "wsproto" | "websockets" | "none"
        # loop = "auto"        # "auto" | "asyncio" | "uvloop"

    class auth(AquilaConfig.Auth):
        secret_key      = Secret(env="AQ_SECRET_KEY", default="change-me-in-prod")
        password_hasher = AquilaConfig.PasswordHasher(algorithm="argon2id")
        backends        = [
            "aquilia.auth.backends.TokenBackend",
            "aquilia.auth.backends.SessionBackend",
        ]

    class di(AquilaConfig.DI):
        # Dependency-injection container tuning. See AquilaConfig.DI
        # for every option and its default.
        scope_enforcement   = "warn"   # "warn" | "raise" | "off"
        parallel_resolution = False    # gather independent ctor deps
        diagnostics_enabled = False    # emit resolution events
        # disposal_strategy   = "lifo"   # "lifo" | "fifo" | "parallel"
        # pool_max_waiters    = None     # cap waiters on exhausted pools

class DevEnv(BaseEnv):
    """Development — hot-reload, debug pages, single worker."""
    env = "dev"

    class server(BaseEnv.server):
        debug   = True
        reload  = True
        workers = 1

    class di(BaseEnv.di):
        # Trace DI resolution in dev; keep enforcement lenient.
        diagnostics_enabled = True

class ProdEnv(BaseEnv):
    """Production — multi-worker, no reload, no debug."""
    env = "prod"

    class server(BaseEnv.server):
        host               = Env("AQ_HOST", default="0.0.0.0")
        port               = Env("AQ_PORT", default=8000, cast=int)
        workers            = Env("AQ_WORKERS", default=4, cast=int)
        reload             = False
        access_log         = False
        timeout_keep_alive = 30
        limit_max_requests = 10_000   # auto-restart workers after 10k requests
        proxy_headers      = True     # trust X-Forwarded-* from load balancer

    class auth(BaseEnv.auth):
        secret_key = Secret(env="AQ_SECRET_KEY", required=True)

    class di(BaseEnv.di):
        # Fail-fast on captive-dependency scope violations in prod,
        # and parallelise independent constructor dependencies.
        scope_enforcement   = "raise"
        parallel_resolution = True

# ── Workspace Structure ──────────────────────────────────────────

workspace = (
    Workspace(
        name="rest_api_contract",
        version="1.0.0",
        description="Aquilia workspace",
    )
    # Wire environment config (resolved by AQ_ENV at runtime)
    .env_config(BaseEnv)

    # Starter module -- registered here so the server does not need
    # to hard-code it. Delete this line (and starter.py) once you
    # add your own modules with a GET "/" route.
    .starter("starter")

    .inspector(enabled=True)

    # Add modules here with explicit configuration:
    # .module(Module("auth", version="1.0.0", description="Authentication module").route_prefix("/api/v1/auth").depends_on("core"))
    # .module(Module("users", version="1.0.0", description="User management").route_prefix("/api/v1/users").depends_on("auth", "core"))

    # Middleware chain -- controls which middleware runs and in what order.
    # Presets: defaults() (dev), production(), minimal()
    # Custom: MiddlewareChain.chain().use("aquilia.middleware.ExceptionMiddleware", priority=1).use(...)
    .middleware(MiddlewareChain.defaults())

    # ---- Modules ---------------------------------------------------------

    .module(Module("rest", version="0.1.0", description="Rest module")
        .route_prefix("/rest")
        .tags("rest"))

    # Integrations - Configure core systems
    .integrate(DiIntegration(auto_wire=True))
    .integrate(RegistryIntegration())
    .integrate(RoutingIntegration(strict_matching=True))
    .integrate(FaultHandlingIntegration(default_strategy="propagate"))
    .integrate(PatternsIntegration())

    # Database - Configure the ORM backend
    .integrate(DatabaseIntegration(
        url="sqlite:///db.sqlite3",       # SQLite (dev)
        # url="postgresql://user:pass@localhost:5432/rest_api_contract",  # PostgreSQL
        pool_size=5,
        echo=False,
        auto_migrate=False,
    ))

    # Cache - In-memory by default, switch to Redis for production
    .integrate(CacheIntegration(
        backend="memory",
        default_ttl=300,
        max_size=1024,
        key_prefix="rest_api_contract:",
    ))

    # Templates - Fluent configuration
    .integrate(
        TemplatesIntegration.builder()
        .source("templates")
        .scan_modules()
        .cached("memory")
        .secure()
    )

    # Static Files - Serve static assets (CSS, JS, images)
    .integrate(StaticFilesIntegration(
        directories={"/static": "static"},
        cache_max_age=86400,
        etag=True,
    ))

    # Sessions (uncomment to enable session management)
    # .sessions(
    #     policies=[
    #         SessionPolicy(
    #             name="default",
    #             ttl=timedelta(days=7),
    #             idle_timeout=timedelta(hours=1),
    #             absolute_timeout=timedelta(days=30),
    #             rotate_on_use=False,
    #             rotate_on_privilege_change=True,
    #             fingerprint_binding=False,
    #             scope="user",
    #             persistence=PersistencePolicy(
    #                 enabled=True,
    #                 store_name="default",
    #                 write_through=True,
    #                 compress=False,
    #             ),
    #             concurrency=ConcurrencyPolicy(
    #                 max_sessions_per_principal=5,
    #                 behavior_on_limit="evict_oldest",
    #             ),
    #             transport=TransportPolicy(
    #                 cookie_name="rest_api_contract_session",
    #                 cookie_secure=False,
    #                 cookie_httponly=True,
    #                 cookie_samesite="lax",
    #             ),
    #         ),
    #     ],
    # )

    # Security (uncomment to enable security middleware)
    # Fine-grained: use Integration.cors(), Integration.csp(),
    # Integration.rate_limit() with .integrate().
    # .security(
    #     cors_enabled=False,
    #     csrf_protection=False,
    #     helmet_enabled=True,
    #     rate_limiting=False,
    # )

    # Telemetry (uncomment to enable observability)
    # .telemetry(
    #     tracing_enabled=False,
    #     metrics_enabled=True,
    #     logging_enabled=True,
    # )

    # Admin Dashboard (uncomment to enable admin at /admin/)
    # Requires: aq admin createsuperuser
    # .integrate(AdminIntegration(
    #     url_prefix="/admin",
    #     site_title="rest_api_contract Admin",
    #     auto_discover=True,
    # ))

    .integrate(
        SpeculaIntegration(title="Rest API")
    )
)

# Export for CLI/server
__all__ = ["workspace"]
