import { useTheme } from '../../../context/ThemeContext'
import { CodeBlock } from '../../../components/CodeBlock'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Code, ShieldCheck } from 'lucide-react'
import { NextSteps } from '../../../components/NextSteps'

export function MailTemplates() {
  const { theme } = useTheme()
  const isDark = theme === 'dark'
  const textMuted = isDark ? 'text-gray-400' : 'text-gray-600'
  const borderMuted = isDark ? 'border-white/5' : 'border-gray-100'

  return (
    <div className="max-w-4xl mx-auto px-4 py-2">
      {/* Header */}
      <div className="mb-12">
        <div className="flex items-center gap-2 text-sm text-aquilia-500 font-medium mb-4">
          <Code className="w-4 h-4" />
          Mail / Templates
        </div>
        <h1 className={`text-4xl font-extrabold tracking-tight mb-4 ${isDark ? 'text-white' : 'text-gray-900'}`}>
          <span className="gradient-text font-mono">Aquilia Template Syntax (ATS)</span>
        </h1>
        <p className={`text-lg leading-relaxed ${textMuted}`}>
          AquilaMail templates use Aquilia Template Syntax (ATS) — an expression and filter engine with mandatory HTML autoescaping by default. Control flow structures are prohibited so template rendering stays safe and deterministic.
        </p>
      </div>

      {/* Overview & Security */}
      <section className="mb-16">
        <h2 className={`text-2xl font-bold tracking-tight mb-6 pb-2 border-b ${borderMuted} ${isDark ? 'text-white' : 'text-gray-900'}`}>
          Expression-Only Design &amp; Security
        </h2>
        <p className={`text-sm mb-4 ${textMuted}`}>
          ATS is deliberately minimal: it supports expressions and filter applications only. There are no loops (<code className="text-aquilia-400">for</code>), conditionals (<code className="text-aquilia-400">if</code>), or layout inheritance. Any attempt to use control flow tags raises <code className="text-aquilia-400">MailTemplateFault</code> at render time rather than silently shipping unparsed tags to a user's inbox.
        </p>
        <div className="p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/10 flex items-start gap-3">
          <ShieldCheck className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
          <p className={`text-xs leading-relaxed ${textMuted}`}>
            <strong>Automatic HTML Autoescaping:</strong> All interpolated expressions are automatically HTML-escaped using <code className="text-aquilia-400">html.escape()</code> (including double and single quotes). To bypass escaping for pre-sanitized HTML fragments, append <code className="text-aquilia-400">| safe</code>.
          </p>
        </div>
      </section>

      {/* Syntax Examples */}
      <section className="mb-16">
        <h2 className={`text-2xl font-bold tracking-tight mb-6 pb-2 border-b ${borderMuted} ${isDark ? 'text-white' : 'text-gray-900'}`}>
          ATS Syntax Reference
        </h2>
        <div className="space-y-8">
          {[
            {
              syntax: '<< expr >>',
              desc: 'Expression interpolation with automatic HTML escaping. Supports dict keys and attribute access (e.g. user.profile.name). Undefined values resolve to empty strings.',
              code: `<!-- Context: {"user": {"name": "<b>Asha</b>"}} -->
<p>Hi << user.name >>!</p>
<!-- Output: <p>Hi &lt;b&gt;Asha&lt;/b&gt;!</p> -->`
            },
            {
              syntax: '<< expr | filter >>',
              desc: 'Applies a filter to an expression. Built-in filters include title, upper, lower, trim, length, default, currency, escape, safe.',
              code: `<!-- Context: {"price": 12.5, "title": "welcome guide"} -->
<p><< title | title >>: << price | currency('USD') >></p>
<!-- Output: <p>Welcome Guide: USD 12.50</p> -->`
            },
            {
              syntax: '<< expr | safe >>',
              desc: 'Explicit opt-out of HTML autoescaping. Only use with trusted HTML content generated by your own application.',
              code: `<!-- Context: {"body_html": "<strong>Your account is active.</strong>"} -->
<div><< body_html | safe >></div>
<!-- Output: <div><strong>Your account is active.</strong></div> -->`
            }
          ].map((item, i) => (
            <div key={i} className="py-4 border-b border-white/5 last:border-0">
              <h3 className={`font-semibold text-sm mb-2 ${isDark ? 'text-white' : 'text-gray-900'} font-mono`}>
                {item.syntax}
              </h3>
              <p className={`text-sm mb-3 ${textMuted}`}>{item.desc}</p>
              <CodeBlock language="html">{item.code}</CodeBlock>
            </div>
          ))}
        </div>
      </section>

      {/* Public Python API */}
      <section className="mb-16">
        <h2 className={`text-2xl font-bold tracking-tight mb-6 pb-2 border-b ${borderMuted} ${isDark ? 'text-white' : 'text-gray-900'}`}>
          Documented ATS Python API (<code className="text-aquilia-400">aquilia.mail.template</code>)
        </h2>
        <p className={`text-sm mb-6 ${textMuted}`}>
          Render strings, render template files, or extend ATS with custom registered filters directly from Python:
        </p>
        <CodeBlock
          language="python"
          filename="ats_api_usage.py"
          highlightLines={[7, 10, 16, 21]}
        >{`from aquilia.mail.template import (
    configure, render_string, render_template, register_filter, FILTERS
)

# 1. Configure template search paths
configure(["mail_templates", "modules/auth/templates"])

# 2. Render inline template string
html_out = render_string(
    "Hello << user.name | title >>, total: << amount | currency >>",
    {"user": {"name": "asha"}, "amount": 49.99}
)

# 3. Render template file from configured directories
rendered = render_template("welcome.aqt", {"user": user_dict})

# 4. Register custom filter
@register_filter("mask_card")
def mask_card_filter(value: str) -> str:
    return f"•••• •••• •••• {str(value)[-4:]}"

# Now usable in templates: << card_number | mask_card >>`}</CodeBlock>
      </section>

      {/* Built-in Filters */}
      <section className="mb-16">
        <h2 className={`text-2xl font-bold tracking-tight mb-6 pb-2 border-b ${borderMuted} ${isDark ? 'text-white' : 'text-gray-900'}`}>
          Built-in ATS Filters
        </h2>
        <div className="overflow-x-auto rounded-2xl border border-white/5 bg-white/5 backdrop-blur-sm shadow-xl">
          <table className={`w-full text-sm ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
            <thead>
              <tr className="border-b border-white/5 bg-white/5">
                <th className="text-left py-4 px-6 font-semibold text-aquilia-500 w-32">Filter</th>
                <th className="text-left py-4 px-6">Signature</th>
                <th className="text-left py-4 px-6">Description</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {[
                ['currency', 'currency(code="USD")', 'Formats numeric values as currency strings.'],
                ['default', 'default(fallback)', 'Returns fallback if value is None or empty string.'],
                ['escape', 'escape', 'Explicitly HTML escapes a string.'],
                ['join', 'join(delimiter=", ")', 'Joins list elements into a single string.'],
                ['length', 'length', 'Returns length of string, list, or dict.'],
                ['lower', 'lower', 'Converts text to lowercase.'],
                ['upper', 'upper', 'Converts text to uppercase.'],
                ['title', 'title', 'Capitalizes the first character of each word.'],
                ['trim', 'trim', 'Strips leading and trailing whitespace.'],
                ['truncate', 'truncate(length=50)', 'Truncates text to specified length.'],
                ['safe', 'safe', 'Marks output as safe from autoescaping.'],
              ].map(([filterName, sig, desc], i) => (
                <tr key={i} className="hover:bg-white/5 transition-colors duration-150">
                  <td className="py-3.5 px-6 font-mono font-semibold text-xs text-aquilia-400">{filterName}</td>
                  <td className="py-3.5 px-6 font-mono text-xs">{sig}</td>
                  <td className={`py-3.5 px-6 text-xs ${textMuted}`}>{desc}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Navigation */}
      <div className={`flex items-center justify-between pt-8 mt-12 border-t ${borderMuted}`}>
        <Link to="/docs/mail/providers" className={`flex items-center gap-2 text-sm ${isDark ? 'text-gray-400 hover:text-white' : 'text-gray-500 hover:text-gray-900'}`}>
          <ArrowLeft className="w-4 h-4" /> Providers
        </Link>
        <Link to="/docs/mail/delivery" className="flex items-center gap-2 text-sm text-aquilia-500 font-semibold hover:text-aquilia-400">
          Delivery &amp; Bounces <ArrowRight className="w-4 h-4" />
        </Link>
      </div>

      <NextSteps
        items={[
          { text: 'Delivery Queue & Bounce Suppression', link: '/docs/mail/delivery' },
          { text: 'MailService & Dispatch Options', link: '/docs/mail/service' },
          { text: 'Mail Providers (SMTP, SES, SendGrid)', link: '/docs/mail/providers' },
        ]}
      />
    </div>
  )
}