"""
Aquilia ASGI Runtime -- myapp
============================

Auto-generated by ``aq run``.  DO NOT EDIT -- regenerated on every launch.

Timestamp : 2026-03-06 00:00:30
Workspace : myapp
Mode      : dev
Modules   : 0 (none)

Usage
-----
Development  : aq run
Production   : uvicorn runtime.app:app --host 0.0.0.0 --port 8000 --workers 4
Gunicorn     : gunicorn runtime.app:app -k uvicorn.workers.UvicornWorker -w 4
Hypercorn    : hypercorn runtime.app:app --bind 0.0.0.0:8000
Docker       : CMD ["uvicorn", "runtime.app:app", "--host", "0.0.0.0"]
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

# ────────────────────────────────────────────────────────────────────────
# 1. Path & environment bootstrap
# ────────────────────────────────────────────────────────────────────────
_WORKSPACE_ROOT = Path(__file__).resolve().parent.parent

if str(_WORKSPACE_ROOT) not in sys.path:
    sys.path.insert(0, str(_WORKSPACE_ROOT))

os.environ.setdefault("AQUILIA_ENV", "dev")
os.environ.setdefault("AQUILIA_WORKSPACE", str(_WORKSPACE_ROOT))

# ────────────────────────────────────────────────────────────────────────
# 2. Logging -- structured, mode-aware
# ────────────────────────────────────────────────────────────────────────
_LOG_LEVEL = logging.DEBUG if "dev" == "dev" else logging.INFO
_LOG_FORMAT = (
    "%(asctime)s | %(levelname)-8s | %(name)s -- %(message)s"
    if "dev" == "prod"
    else "%(levelname)-8s | %(name)s -- %(message)s"
)
logging.basicConfig(level=_LOG_LEVEL, format=_LOG_FORMAT, force=True)

# Silence noisy third-party loggers in dev mode
for _noisy in ("aiosqlite", "asyncio", "urllib3", "httpcore", "httpx",
               "watchfiles", "uvicorn.error", "python_multipart",
               "python_multipart.multipart"):
    logging.getLogger(_noisy).setLevel(logging.WARNING)

_logger = logging.getLogger("aquilia.runtime")

# ────────────────────────────────────────────────────────────────────────
# 3. Configuration -- single source of truth from workspace.py
# ────────────────────────────────────────────────────────────────────────
from aquilia.config import ConfigLoader

config = ConfigLoader.load(
    paths=["workspace.py"],
    overrides={
        "mode": "dev",
        "debug": True,
    },
)

# Ensure ``apps`` namespace exists for every known module
if "apps" not in config.config_data:
    config.config_data["apps"] = {}
for _mod_name in []:
    config.config_data["apps"].setdefault(_mod_name, {})

config._build_apps_namespace()

# ────────────────────────────────────────────────────────────────────────
# 4. Manifest discovery
#    Static imports for known modules (fast path) + dynamic fallback
#    for modules added after the last ``aq run``.
# ────────────────────────────────────────────────────────────────────────

_manifests: list = []
_known_modules: set = {}

# Dynamic discovery -- pick up any *new* modules transparently
_modules_dir = _WORKSPACE_ROOT / "modules"
if _modules_dir.is_dir():
    for _pkg in sorted(_modules_dir.iterdir()):
        if (
            _pkg.is_dir()
            and _pkg.name not in _known_modules
            and (_pkg / "manifest.py").exists()
            and not _pkg.name.startswith(("_", "."))
        ):
            try:
                import importlib
                _mod = importlib.import_module(f"modules.{_pkg.name}.manifest")
                _m = getattr(_mod, "manifest", None)
                if _m is not None:
                    _manifests.append(_m)
                    config.config_data["apps"].setdefault(_pkg.name, {})
                    _logger.info("Auto-discovered module: %s", _pkg.name)
            except Exception as _exc:
                _logger.warning(
                    "Could not import manifest for module %s: %s",
                    _pkg.name, _exc,
                )

    # Rebuild apps namespace after potential new modules
    config._build_apps_namespace()

# ────────────────────────────────────────────────────────────────────────
# 5. Server construction
# ────────────────────────────────────────────────────────────────────────
from aquilia import AquiliaServer
from aquilia.aquilary.core import RegistryMode

_MODE_MAP = {"dev": RegistryMode.DEV, "prod": RegistryMode.PROD, "test": RegistryMode.TEST}
_registry_mode = _MODE_MAP.get("dev", RegistryMode.DEV)

server = AquiliaServer(
    manifests=_manifests,
    config=config,
    mode=_registry_mode,
)

# ────────────────────────────────────────────────────────────────────────
# 6. ASGI application export
# ────────────────────────────────────────────────────────────────────────
app = server.app
