"""
Auto-generated Aquilia ASGI Application
========================================

This file is automatically generated by the Aquilia CLI from your workspace configuration.
It creates an ASGI-compliant application that can be run with any ASGI server.

Generated by: aq run
Workspace: aquilia-workspace
Timestamp: 2026-03-03 12:45:20

DO NOT EDIT - This file is regenerated on each run.

Usage:
  Development: aq run
  Production:  uvicorn runtime.app:app --workers 4
  With gunicorn: gunicorn runtime.app:app -k uvicorn.workers.UvicornWorker

Learn more: https://docs.aquilia.dev/
"""

import sys
from pathlib import Path

# Add workspace root to path
workspace_root = Path(__file__).parent.parent
if str(workspace_root) not in sys.path:
    sys.path.insert(0, str(workspace_root))

from aquilia import AquiliaServer
from aquilia.config import ConfigLoader

from modules.authentication.manifest import manifest as authentication_manifest

# Create configuration
config = ConfigLoader.load(paths=["workspace.py"])

# Merge config data directly
config.config_data["debug"] = True
config.config_data["mode"] = "dev"

# Initialize apps config for each module
config.config_data["apps"] = {}
config.config_data["apps"]["authentication"] = {}

# Build the apps namespace (required by Aquilary)
config._build_apps_namespace()

# Determine registry mode from config
from aquilia.aquilary.core import RegistryMode
_mode_str = config.config_data.get("mode", "dev")
_registry_mode = RegistryMode(_mode_str) if _mode_str in ("dev", "prod", "test") else RegistryMode.DEV

# Create server with all module manifests
server = AquiliaServer(
    manifests=[authentication_manifest],
    config=config,
    mode=_registry_mode,
)

# ASGI application
app = server.app

print("✓ Aquilia workspace app loaded")
print(f"  Workspace: aquilia-workspace")
print(f"  Modules: 1")
