import { useTheme } from '../../../context/ThemeContext'
import { CodeBlock } from '../../../components/CodeBlock'
import { DocTerm } from '../../../components/docPreview/DocTerm'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Zap } from 'lucide-react'
import { NextSteps } from '../../../components/NextSteps'

export function SSEOpenAIStreaming() {
  const { theme } = useTheme()
  const isDark = theme === 'dark'
  const textMuted = isDark ? 'text-gray-400' : 'text-gray-600'
  const borderMuted = isDark ? 'border-white/5' : 'border-gray-100'

  return (
    <div className="max-w-4xl mx-auto py-6 font-sans">
      {/* Header */}
      <div className="mb-12">
        <div className="flex items-center gap-2 text-sm text-aquilia-500 font-mono mb-4">
          <Zap className="w-4 h-4" />
          <span>SSE SYSTEM / OPENAI STREAMING</span>
        </div>
        <h1 className={`text-4xl font-light tracking-tight mb-4 ${isDark ? 'text-white' : 'text-gray-900'}`}>
          AI Streaming with OpenAI
        </h1>
        <p className={`text-lg leading-relaxed font-light ${textMuted}`}>
          Implement real-time ChatGPT-style chat streaming by connecting OpenAI's async client stream to Aquilia's SSEResponse engine.
        </p>
      </div>

      {/* Overview */}
      <section className="mb-16">
        <h2 className="text-xl font-mono text-aquilia-400 uppercase tracking-wider mb-6">Scenario Integration</h2>
        <div className={`space-y-6 font-light leading-relaxed ${textMuted}`}>
          <p>
            When building generative AI interfaces, displaying completion blocks after a long wait ruins the user experience. By streaming individual response tokens as they are generated by models (like <code className="text-white">gpt-4o</code>), the page feels instantaneous.
          </p>
          <p>
            This scenario demonstrates how to invoke OpenAI's asynchronous stream API inside an Aquilia controller method, capture tokens sequentially, and tunnel them directly to client browsers using <DocTerm id="sse.SSEResponse">SSEResponse.text</DocTerm>.
          </p>
        </div>
      </section>

      {/* Python Controller Implementation */}
      <section className="mb-16">
        <h2 className="text-xl font-mono text-aquilia-400 uppercase tracking-wider mb-6">Backend Controller</h2>
        <p className={`mb-6 font-light leading-relaxed ${textMuted}`}>
          The controller action reads the prompt parameter, initializes the async OpenAI client, and returns a token generator stream:
        </p>

        <CodeBlock language="python" filename="controllers/openai_chat.py" highlightLines={[17, 20, 24, 25]}>{`import os
from openai import AsyncOpenAI
from aquilia.controller import Controller, GET, RequestCtx
from aquilia.sse import SSEResponse

class OpenAIChatController(Controller):
    def initialize(self):
        # Initialize OpenAI async client
        self.client = AsyncOpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

    @GET("/sse/chat")
    async def chat_stream(self, ctx: RequestCtx):
        prompt = ctx.query.get("prompt", "Tell me a joke.")
        
        # Stream response back to the client
        return SSEResponse.text(self._openai_token_generator(prompt))

    async def _openai_token_generator(self, prompt: str):
        # Request completion stream from OpenAI API
        stream = await self.client.chat.completions.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}],
            stream=True
        )
        
        # Iterate over stream chunks asynchronously and yield content
        async for chunk in stream:
            token = chunk.choices[0].delta.content or ""
            if token:
                yield token`}</CodeBlock>
      </section>

      {/* HTML/JS frontend */}
      <section className="mb-16">
        <h2 className="text-xl font-mono text-aquilia-400 uppercase tracking-wider mb-6">Frontend Client Integration</h2>
        <p className={`mb-6 font-light leading-relaxed ${textMuted}`}>
          On the browser side, query the chat stream endpoint and append tokens to your DOM elements:
        </p>

        <CodeBlock language="javascript" filename="chat_client.js" highlightLines={[6, 9, 14]}>{`function startChatStream(userPrompt) {
    const chatContainer = document.getElementById("chat-box");
    const encodedPrompt = encodeURIComponent(userPrompt);
    
    // Connect to Aquilia SSE Chat endpoint
    const eventSource = new EventSource(\`/sse/chat?prompt=\${encodedPrompt}\`);

    eventSource.onmessage = (event) => {
        // Append tokens dynamically to container
        chatContainer.innerText += event.data;
    };

    eventSource.onerror = (error) => {
        console.log("Chat connection complete or disconnected.");
        eventSource.close();
    };
}`}</CodeBlock>
      </section>

      {/* Navigation */}
      <div className={`flex items-center justify-between pt-8 mt-12 border-t ${borderMuted}`}>
        <Link to="/docs/sse/streams" className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors">
          <ArrowLeft className="w-4 h-4" /> Text &amp; JSON Streams
        </Link>
        <Link to="/docs/sse/resources" className="flex items-center gap-2 text-sm text-aquilia-500 font-semibold hover:text-aquilia-400 transition-colors">
          Resource Management <ArrowRight className="w-4 h-4" />
        </Link>
      </div>

      <NextSteps />
    </div>
  )
}
