"""
Aquilia migrations -- migration file writing and loading.

Writes a :class:`~aquilia.models.migration.graph.MigrationNode` to disk as a
Python module, and reads one back.

The rendering itself lives in :mod:`aquilia.models.migration.codegen`, which
emits real constructor calls -- ``fields.CharField(max_length=200)`` -- rather
than a serialized dict. This module owns the surrounding file: its header, its
``Meta`` block, and the import list the rendered body needs.

Determinism
-----------
No clock, hostname, or hash-ordered collection enters the file body.
Regenerating a migration from unchanged models produces a byte-identical file,
which is what lets "no changes detected" be trusted.
"""

from __future__ import annotations

import importlib
import importlib.util
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from aquilia.faults.domains import MigrationFault
from aquilia.models.migration.codegen import collect_imports, render_operations, render_string, render_value
from aquilia.models.migration.operations import Operation

if TYPE_CHECKING:
    from aquilia.models.migration.graph import MigrationNode

__all__ = [
    "serialize_operations",
    "render_migration_module",
    "load_migration_module",
    "revision_from_path",
    "slug_from_path",
    "MIGRATION_TEMPLATE_VERSION",
]


MIGRATION_TEMPLATE_VERSION = 3
"""Version of the generated-file layout, written into each migration.

Bumped to 3 when generated files moved from serialized dicts to real
constructor calls. Both load correctly -- a dict entry in an existing file is
still accepted by :func:`load_migration_module` -- so the version is
informational rather than a gate.
"""

_INDENT = "    "


# ── Operation serialization ─────────────────────────────────────────────────


def serialize_operations(operations: tuple[Operation, ...] | list[Operation]) -> str:
    """Render operations as the body of a migration file's ``operations`` list.

    Args:
        operations: The operations to render, in application order.

    Returns:
        Source text for the assignment, one entry per operation.

    Raises:
        MigrationFault: If an operation contains a value with no source form.

    Example:
        >>> print(serialize_operations([AddField(model="U", field=bio)]))
        operations: list[Operation] = [
            AddField(model="U", field=ColumnState.of("bio", fields.TextField())),
        ]
    """
    return render_operations(operations)


# ── Module rendering ────────────────────────────────────────────────────────


def render_migration_module(
    node: MigrationNode,
    *,
    generated_at: str | None = None,
) -> str:
    """Render a complete migration file as Python source.

    The body is rendered first and the import list derived from it, so a file
    imports exactly the names it uses -- no unused imports, and no blanket
    ``noqa`` to hide them.

    Args:
        node: The migration to render.
        generated_at: ISO-8601 timestamp for the file header comment. Passed in
            rather than read from the clock so that regenerating a migration
            from unchanged models produces a byte-identical file -- a timestamp
            baked in here would make every regeneration look like a change.

    Returns:
        The complete module source, ending in a newline.

    Raises:
        MigrationFault: If an operation contains a value with no source form.

    Example:
        >>> source = render_migration_module(node)
        >>> Path("migrations/0002_add_bio.py").write_text(source)
    """
    body = render_operations(node.operations)

    models = sorted(
        {
            model
            for operation in node.operations
            for model in (
                getattr(operation, "model", None),
                getattr(operation, "new_model", None),
            )
            if model
        }
    )

    lines = [
        '"""',
        f"Migration {node.name}",
        "",
        f"Models: {', '.join(models) if models else '(none)'}",
    ]
    if generated_at:
        lines.append(f"Generated: {generated_at}")
    lines.extend(
        [
            "",
            "Generated by Aquilia. Edit by hand only if you understand the",
            "consequences -- the applied-migration checksum will change.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
        ]
    )
    lines.extend(collect_imports(node.operations, body))
    lines.extend(
        [
            # One blank line before a plain assignment, two before a class --
            # what isort and PEP 8 want, so generated files lint clean.
            "",
            f"TEMPLATE_VERSION = {MIGRATION_TEMPLATE_VERSION}",
            "",
            "",
            "class Meta:",
            f'{_INDENT}"""Migration metadata read by the migration runner."""',
            "",
            f"{_INDENT}revision = {render_string(node.revision)}",
            f"{_INDENT}slug = {render_string(node.slug)}",
            f"{_INDENT}dependencies = {render_value(list(node.dependencies), indent=1)}",
            f"{_INDENT}replaces = {render_value(list(node.replaces), indent=1)}",
            f"{_INDENT}atomic = {node.atomic!r}",
            "",
            "",
            "",
        ]
    )

    return "\n".join(lines) + body + "\n"


# ── Module loading ──────────────────────────────────────────────────────────


def _find_workspace_root(path: Path) -> Path | None:
    """Find the workspace that owns a migration file.

    Migration directories may be nested or configured outside the conventional
    ``migrations/`` location, so the search starts at the migration file and
    then falls back to the command's working directory. A workspace is identified
    by the same Python-native markers accepted by the CLI: ``workspace.py`` or
    ``aquilia.py``.

    Args:
        path: Migration file whose workspace should be located.

    Returns:
        The resolved workspace root, or ``None`` when no workspace marker exists.
    """
    starts = (path.resolve().parent, Path.cwd().resolve())
    visited: set[Path] = set()
    for start in starts:
        for candidate in (start, *start.parents):
            if candidate in visited:
                continue
            visited.add(candidate)
            if (candidate / "workspace.py").is_file() or (candidate / "aquilia.py").is_file():
                return candidate
    return None


def _ensure_workspace_importable(path: Path) -> Path | None:
    """Add a migration's workspace root to ``sys.path`` before deserialization.

    Generated fields may contain durable dotted references to application code,
    such as ``modules.users.models.UserStatus`` for an ``EnumField``. Installed
    console scripts do not guarantee that their current working directory is on
    ``sys.path``, so migration loading must establish workspace importability
    explicitly instead of relying on prior model discovery.

    Args:
        path: Migration file about to be imported.

    Returns:
        The workspace root that was found, or ``None`` outside a workspace.
    """
    workspace_root = _find_workspace_root(path)
    if workspace_root is None:
        return None

    root = str(workspace_root)
    if root not in sys.path:
        sys.path.insert(0, root)
    return workspace_root


def load_migration_module(path: Path) -> MigrationNode:
    """Load a migration file from disk into a :class:`MigrationNode`.

    Args:
        path: Path to the migration module.

    Returns:
        The loaded migration, with its checksum computed from the file bytes so
        an edit after it was applied is detectable.

    Raises:
        MigrationFault: If the file cannot be imported, declares no
            ``operations`` list, or an entry in that list is not an
            :class:`~aquilia.models.migration.operations.Operation`.

    Example:
        >>> node = load_migration_module(Path("migrations/0002_add_bio.py"))
        >>> node.revision
        '0002'
    """
    import hashlib

    from aquilia.models.migration.graph import MigrationNode

    _ensure_workspace_importable(path)
    revision = revision_from_path(path)
    spec = importlib.util.spec_from_file_location(f"aquilia_migration_{revision}", path)
    if spec is None or spec.loader is None:
        raise MigrationFault(
            migration=revision,
            reason=f"Cannot load migration module at {path}: no import spec could be created.",
        )

    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except MigrationFault:
        raise
    except Exception as exc:
        raise MigrationFault(
            migration=revision,
            reason=f"Failed to import migration {path.name}: {exc}",
        ) from exc

    meta = getattr(module, "Meta", None)
    operations = getattr(module, "operations", None)

    if operations is None:
        raise MigrationFault(
            migration=revision,
            reason=(
                f"Migration {path.name} declares no `operations` list. Every migration "
                f"must define one, holding Operation instances."
            ),
        )

    resolved: list[Operation] = []
    for position, entry in enumerate(operations):
        if isinstance(entry, Operation):
            resolved.append(entry)
        elif isinstance(entry, dict):
            # Migrations written before generated files held real constructor
            # calls stored each operation as a dict. Still accepted so an
            # already-applied migration keeps loading; nothing emits this form.
            resolved.append(Operation.from_dict(entry))
        else:
            raise MigrationFault(
                migration=revision,
                reason=(
                    f"Migration {path.name} entry {position} is {type(entry).__name__}, "
                    f"not an Operation. Every entry in `operations` must be an instance "
                    f"of aquilia.models.migration.operations.Operation."
                ),
            )

    checksum = hashlib.sha256(path.read_bytes()).hexdigest()[:16]

    return MigrationNode(
        revision=getattr(meta, "revision", revision) if meta else revision,
        slug=getattr(meta, "slug", slug_from_path(path)) if meta else slug_from_path(path),
        operations=tuple(resolved),
        dependencies=tuple(getattr(meta, "dependencies", ()) if meta else ()),
        replaces=tuple(getattr(meta, "replaces", ()) if meta else ()),
        atomic=bool(getattr(meta, "atomic", True)) if meta else True,
        source_path=path,
        checksum=checksum,
    )


def revision_from_path(path: Path) -> str:
    """Extract the revision from a migration filename.

    Accepts both ``YYYYMMDD_HHMMSS_slug.py`` and ``NNNN_slug.py``.

    Args:
        path: The migration file path.

    Returns:
        The revision identifier.
    """
    parts = path.stem.split("_")
    if len(parts) >= 2 and parts[0].isdigit() and len(parts[0]) == 8 and parts[1].isdigit():
        return f"{parts[0]}_{parts[1]}"
    return parts[0] if parts else path.stem


def slug_from_path(path: Path) -> str:
    """Extract the slug from a migration filename."""
    revision = revision_from_path(path)
    stem = path.stem
    if stem.startswith(revision):
        return stem[len(revision) :].lstrip("_")
    return stem
