"""
Aquilia Contract stub generation -- ``.pyi`` emission for static type checkers.

A Contract resolves its fields at class-body evaluation time, and an instance
exposes them through ``__getattr__``. Both are invisible to a static analyser:
``mypy`` and ``pyright`` see ``UserContract(...).email`` as ``Any`` at best,
and as an attribute error under ``--strict`` at worst.

This module closes that gap without a bespoke type-checker plugin. It walks a
module's Contract classes at runtime — after ``ContractMeta`` has compiled
them, so every facet is resolved — and emits a ``.pyi`` stub declaring each
field with the Python type its facet *produces*. ``IntFacet`` accepts the
string ``"42"`` on the wire but yields ``int``, and the stub says ``int``.

A ``.pyi`` is a portable artifact: every type checker consumes it, no plugin
needs installing, and it is checked into the repository like any other
generated file.

Usage::

    aq contracts stubs myapp.contracts            # write myapp/contracts.pyi
    aq contracts stubs myapp.contracts --check     # fail if out of date (CI)

Limitations:
    A ``.pyi`` *replaces* its module for the type checker — it does not
    augment it. This generator therefore reproduces the whole module surface,
    not only its Contracts: import statements are replayed from the source
    AST, and module-level classes, functions, and constants are emitted with
    their runtime signatures. Anything it cannot render faithfully is emitted
    as ``Any`` and listed in :attr:`StubReport.degraded`, so a lost annotation
    is reported rather than silently weakening the module's types.
"""

from __future__ import annotations

import ast
import enum
import inspect
import sys
from dataclasses import dataclass, field
from pathlib import Path
from types import ModuleType
from typing import Any

__all__ = [
    "StubReport",
    "contract_stub_body",
    "generate_module_stub",
    "write_module_stub",
]

_HEADER = (
    "# Generated by `aq contracts stubs`. Do not edit by hand.\n"
    "# Regenerate after changing the Contract declarations in the paired module.\n"
)

#: Emitted unconditionally: facet-derived annotations use ``Any`` as their
#: fallback and ``Literal`` for choice/constant facets.
_BASE_IMPORTS = "from typing import Any, Literal\n"


@dataclass(frozen=True, slots=True)
class StubReport:
    """
    Outcome of generating one module's stub.

    Attributes:
        module: Dotted name of the module the stub describes.
        source: The ``.pyi`` text.
        path: Where the stub belongs, alongside the module's ``.py``.
        contracts: Names of the Contract classes that were stubbed.
        degraded: Members whose types could not be rendered faithfully and were
            emitted as ``Any``, each as ``"name: reason"``. A non-empty list is
            not an error, but it names exactly what the stub does not know.
    """

    module: str
    source: str
    path: Path
    contracts: tuple[str, ...] = ()
    degraded: tuple[str, ...] = ()

    @property
    def is_current(self) -> bool:
        """True if the on-disk stub already matches :attr:`source`."""
        try:
            return self.path.read_text(encoding="utf-8") == self.source
        except FileNotFoundError:
            return False


@dataclass(slots=True)
class _Emitter:
    """Accumulates stub lines plus the imports and degradations they imply."""

    lines: list[str] = field(default_factory=list)
    imports: set[str] = field(default_factory=set)
    degraded: list[str] = field(default_factory=list)

    def annotate(self, text: str) -> str:
        """Record the imports an annotation needs and return it unchanged."""
        self.imports.update(_imports_for(text))
        return text


# ---------------------------------------------------------------------------
# Import resolution
# ---------------------------------------------------------------------------


def _imports_for(annotation: str) -> set[str]:
    """
    Modules that must be imported for ``annotation`` to resolve in a stub.

    Facets fully qualify the types they produce (``decimal.Decimal``,
    ``myapp.enums.Colour``), so the import is the longest dotted prefix that is
    a real module. The owning module is already imported at generation time —
    that is what makes the facets inspectable — so ``sys.modules`` answers
    exactly, with no filesystem probing and no risk of importing something new
    as a side effect of generating a stub.

    Args:
        annotation: Annotation source text, e.g. ``"list[decimal.Decimal]"``.

    Returns:
        Module names to import.
    """
    found: set[str] = set()
    for dotted in _dotted_names(annotation):
        parts = dotted.split(".")
        for cut in range(len(parts) - 1, 0, -1):
            candidate = ".".join(parts[:cut])
            if candidate in sys.modules:
                found.add(candidate)
                break
    return found


def _dotted_names(text: str) -> set[str]:
    """Extract dotted identifiers from annotation source text."""
    names: set[str] = set()
    current: list[str] = []
    for char in text:
        if char.isalnum() or char in "._":
            current.append(char)
        else:
            if current:
                names.add("".join(current))
            current = []
    if current:
        names.add("".join(current))
    return {n for n in names if "." in n and not n[0].isdigit()}


# ---------------------------------------------------------------------------
# Contract bodies
# ---------------------------------------------------------------------------


def contract_stub_body(contract_cls: type, emitter: _Emitter | None = None) -> list[str]:
    """
    Stub lines for one Contract's class body.

    Args:
        contract_cls: A compiled Contract subclass.
        emitter: Collector for the imports the annotations need. A throwaway
            one is used when omitted, which is fine for previewing a single
            class but loses the imports the stub would need.

    Returns:
        Indented class-body lines, always at least ``["    ..."]`` so the
        result is syntactically valid even for a Contract with no fields.

    Examples:
        >>> from aquilia.contracts import Contract, TextFacet
        >>> class UserContract(Contract):
        ...     email = TextFacet()
        >>> contract_stub_body(UserContract)
        ['    email: str']
    """
    sink = emitter if emitter is not None else _Emitter()
    body: list[str] = []

    for name, facet in getattr(contract_cls, "_all_facets", {}).items():
        annotation = _facet_annotation(facet, contract_cls, name, sink)
        body.append(f"    {name}: {sink.annotate(annotation)}")

    body.extend(_method_stubs(contract_cls, sink))
    return body or ["    ..."]


def _facet_annotation(facet: Any, owner: type, name: str, sink: _Emitter) -> str:
    """
    Annotation for one facet's validated value, widened for nullability.

    A facet that accepts ``None`` — explicitly via ``allow_null``, or
    implicitly by defaulting to it — must be annotated optional. Omitting that
    is worse than emitting no stub at all: it tells the type checker a value
    can never be ``None`` at exactly the points a caller needs a guard.
    """
    try:
        annotation = facet.python_type()
    except Exception as exc:  # pragma: no cover - defensive
        sink.degraded.append(f"{owner.__name__}.{name}: python_type() raised {type(exc).__name__}")
        return "Any"

    if annotation == "Any":
        sink.degraded.append(f"{owner.__name__}.{name}: {type(facet).__name__} declares no Python type")
        return "Any"

    if getattr(facet, "allow_null", False) or _defaults_to_none(facet):
        return f"{annotation} | None"
    return annotation


def _defaults_to_none(facet: Any) -> bool:
    """True if the facet's declared default is ``None``."""
    from aquilia.contracts.facets import UNSET

    default = getattr(facet, "default", UNSET)
    return default is None


def _method_stubs(cls: type, sink: _Emitter) -> list[str]:
    """
    Signatures for the public methods a class declares itself.

    Inherited methods are left out: the type checker reads the base class from
    its own source (or its own stub) and already knows them. Only what this
    class adds would be lost when the stub shadows the module.
    """
    lines: list[str] = []
    for name, member in vars(cls).items():
        if name.startswith("_") or not inspect.isfunction(member):
            continue
        lines.append(f"    {_signature(member, name, cls.__name__, sink)}")
    return lines


def _signature(fn: Any, name: str, owner: str, sink: _Emitter) -> str:
    """Render one ``def`` line, degrading to ``*args, **kwargs`` if unreadable."""
    try:
        rendered = str(_unquoted(inspect.signature(fn)))
    except (TypeError, ValueError) as exc:
        sink.degraded.append(f"{owner}.{name}: signature unavailable ({type(exc).__name__})")
        return f"def {name}(*args: Any, **kwargs: Any) -> Any: ..."

    sink.imports.update(_imports_for(rendered))
    prefix = "async " if inspect.iscoroutinefunction(fn) else ""
    return f"{prefix}def {name}{rendered}: ..."


class _Raw:
    """Renders its text verbatim where ``inspect`` would apply ``repr``."""

    __slots__ = ("text",)

    def __init__(self, text: str):
        self.text = text

    def __repr__(self) -> str:
        return self.text


def _unquoted(sig: inspect.Signature) -> inspect.Signature:
    """
    Strip the quoting ``from __future__ import annotations`` leaves behind.

    Under PEP 563 every annotation reaches ``inspect`` as a string, so
    ``str(signature)`` renders ``x: int`` as ``x: 'int'``. Both forms are legal
    in a stub, but a file that mixes them looks like a generator defect to
    whoever reviews the diff.
    """

    def unwrap(value: Any) -> Any:
        return _Raw(value) if isinstance(value, str) else value

    params = [p.replace(annotation=unwrap(p.annotation)) for p in sig.parameters.values()]
    return sig.replace(parameters=params, return_annotation=unwrap(sig.return_annotation))


# ---------------------------------------------------------------------------
# Module stubs
# ---------------------------------------------------------------------------


def generate_module_stub(module: ModuleType) -> StubReport:
    """
    Build the ``.pyi`` stub for an already-imported module.

    The module must be imported first: facets are compiled by ``ContractMeta``
    during class-body evaluation, so an unimported module has nothing to
    inspect. Importing it is the caller's job, which keeps this function free
    of import side effects.

    Args:
        module: The imported module.

    Returns:
        A :class:`StubReport` carrying the stub text and everything that had to
        be degraded to ``Any``.

    Raises:
        StubGenerationFault: If the module has no ``__file__`` (a namespace
            package or a synthetic module), so there is nowhere a stub could
            sit and no source to read imports from.
    """
    from aquilia.contracts.core import Contract
    from aquilia.contracts.exceptions import StubGenerationFault

    source_file = getattr(module, "__file__", None)
    if not source_file:
        raise StubGenerationFault(
            f"Module '{module.__name__}' has no source file, so a stub has no location to occupy."
        )

    path = Path(source_file).with_suffix(".pyi")
    sink = _Emitter()
    contracts: list[str] = []

    for name, obj in vars(module).items():
        if name.startswith("_") or getattr(obj, "__module__", None) != module.__name__:
            continue
        if isinstance(obj, type) and issubclass(obj, Contract):
            contracts.append(name)
            sink.lines.extend(_contract_class(obj, module, sink))
        elif isinstance(obj, type):
            sink.lines.extend(_plain_class(obj, sink))
        elif inspect.isfunction(obj):
            sink.lines.append(_signature(obj, name, module.__name__, sink))
            sink.lines.append("")
        else:
            sink.lines.append(f"{name}: Any")
            sink.degraded.append(f"{name}: module-level value emitted as Any")

    text = _assemble(module, source_file, sink)
    return StubReport(
        module=module.__name__,
        source=text,
        path=path,
        contracts=tuple(contracts),
        degraded=tuple(sink.degraded),
    )


def _contract_class(cls: type, module: ModuleType, sink: _Emitter) -> list[str]:
    """Emit one Contract class declaration with its facet-derived fields."""
    bases = ", ".join(_base_name(base, module, sink) for base in cls.__bases__) or "object"
    return [f"class {cls.__name__}({bases}):", *contract_stub_body(cls, sink), ""]


def _plain_class(cls: type, sink: _Emitter) -> list[str]:
    """
    Emit a non-Contract class the module defines.

    Enums keep their members — a stub that drops them turns every
    ``Colour.RED`` in the codebase into an attribute error. Everything else
    gets its public method signatures, which is what callers type against.
    """
    bases = ", ".join(_qualified(base, sink) for base in cls.__bases__) or "object"
    body: list[str] = []

    if isinstance(cls, type) and issubclass(cls, enum.Enum):
        # ``NAME: Colour`` declares an *annotation*, which the typing spec
        # reads as a non-member attribute — mypy then sees an enum with zero
        # members. Assigning the value is what marks it as a member; ``...``
        # stands in when the value has no literal form.
        body.extend(f"    {member.name} = {_literal_or_ellipsis(member.value)}" for member in cls)
    body.extend(_method_stubs(cls, sink))

    return [f"class {cls.__name__}({bases}):", *(body or ["    ..."]), ""]


def _literal_or_ellipsis(value: Any) -> str:
    """Render an enum member's value, or ``...`` if it has no literal form."""
    if value is None or isinstance(value, (str, int, float, bool, bytes)):
        return repr(value)
    return "..."


def _base_name(base: type, module: ModuleType, sink: _Emitter) -> str:
    """Reference a base class, unqualified when it lives in the same module."""
    if getattr(base, "__module__", None) == module.__name__:
        return base.__name__
    return _qualified(base, sink)


def _qualified(obj: type, sink: _Emitter) -> str:
    """Fully-qualified name of a class, recording the import it needs."""
    mod = getattr(obj, "__module__", "")
    name = getattr(obj, "__qualname__", getattr(obj, "__name__", "Any"))
    if not mod or mod == "builtins":
        return name
    if "<locals>" in name:
        sink.degraded.append(f"{name}: locally-defined class emitted as Any")
        return "Any"
    sink.imports.add(mod)
    return f"{mod}.{name}"


def _assemble(module: ModuleType, source_file: str, sink: _Emitter) -> str:
    """Join the header, imports, and emitted declarations into stub text."""
    parts = [_HEADER, "\n", _BASE_IMPORTS]

    replayed = _source_imports(source_file)
    if replayed:
        parts.append("".join(f"{line}\n" for line in replayed))

    # A module imported by the source and also required by an annotation would
    # otherwise be emitted twice; harmless to Python, but a stub with duplicate
    # imports reads as a generator bug to whoever reviews the diff.
    already = set(replayed)
    own = getattr(module, "__name__", "")
    extra = sorted(f"import {name}" for name in sink.imports if name != own)
    extra = [line for line in extra if line not in already]
    if extra:
        parts.append("".join(f"{line}\n" for line in extra))

    parts.append("\n")
    parts.append("\n".join(sink.lines).rstrip())
    parts.append("\n")
    return "".join(parts)


def _source_imports(source_file: str) -> list[str]:
    """
    Replay the module's own import statements into the stub.

    Method signatures are rendered from the runtime objects, and under ``from
    __future__ import annotations`` those come back as the source text the
    module wrote — bare names that only resolve against the module's own
    imports. Replaying them is what keeps those signatures meaningful instead
    of collapsing to ``Any``.

    Returns an empty list if the source cannot be read or parsed: a stub
    missing some imports is still useful, and refusing to generate one because
    a file could not be re-read is not.
    """
    try:
        tree = ast.parse(Path(source_file).read_text(encoding="utf-8"))
    except (OSError, SyntaxError, ValueError):
        return []

    return [
        ast.unparse(node)
        for node in tree.body
        if isinstance(node, (ast.Import, ast.ImportFrom)) and getattr(node, "module", None) != "__future__"
    ]


def write_module_stub(module: ModuleType, *, dry_run: bool = False) -> StubReport:
    """
    Generate a module's stub and write it beside the module's source.

    Args:
        module: The imported module to stub.
        dry_run: Build the report without touching the filesystem. Use with
            :attr:`StubReport.is_current` to fail CI on a stale stub.

    Returns:
        The :class:`StubReport`, whose ``path`` names the file written.
    """
    report = generate_module_stub(module)
    if not dry_run:
        report.path.write_text(report.source, encoding="utf-8")
    return report
