"""
Rest Module.

Generated by: aq add module rest
"""

from .controllers import *
from .services import *
from .faults import *
from .test_routes import *

__module_name__ = "rest"
__version__ = "0.1.0"