"""
Module Manifest: rest
Generated by: aq add module rest

This file is the single source of truth for the rest module.
It controls:

Component Registration:
  - controllers, services, models, middleware, guards, pipes, interceptors

Module-Level Settings (override workspace defaults for this module only):
  - sessions: Module-specific session policies
  - cache: Module-specific cache configuration
  - auth: Module-specific authentication settings
  - templates: Module-specific template directories
  - faults: Module-specific error handling and fault domains

Cross-Module Dependencies:
  - imports: Modules this module depends on
  - exports: Services/components visible to other modules
"""

from aquilia import AppManifest
from aquilia.manifest import (
    FaultHandlingConfig,
    MiddlewareConfig,
    SessionConfig,
    TemplateConfig,
)


manifest = AppManifest(
    # ── Identity ──────────────────────────────────────────────────────
    name="rest",
    version="0.1.0",
    description="Rest module",
    author="",
    tags=["rest"],

    # ── Components ────────────────────────────────────────────────────
    controllers=[
        "modules.rest.controllers:RestController",
    ],
    services=[
        "modules.rest.services:RestService",
    ],
    models=[
        "modules.rest.models:Rest",
    ],
    middleware=[],
    guards=[],
    pipes=[],
    interceptors=[],

    # ── Routing ───────────────────────────────────────────────────────
    # Note: route_prefix is configured in workspace.py via Module.route_prefix()
    base_path="modules.rest",

    # ── Cross-Module Dependencies ─────────────────────
    imports=[],
    exports=[
        # Services/components visible to modules that import this module.
        # "modules.rest.services:RestService",
    ],

    # ── Error Handling (module-level) ─────────────────────────────────
    faults=FaultHandlingConfig(
        default_domain="REST",
        strategy="propagate",
    ),

    # ── Sessions (module-level override) ──────────────────────────────
    # Uncomment to define module-specific session policies:
    # sessions=[
    #     SessionConfig(
    #         name="rest_session",
    #         ttl=timedelta(hours=1),
    #         store="memory",
    #     ),
    # ],

    # ── Templates (module-level) ──────────────────────────────────────
    # Uncomment to add module-specific template directories:
    # templates=TemplateConfig(
    #     search_paths=["modules/rest/templates"],
    # ),

    # ── Auto-Discovery ────────────────────────────────────────────────
    auto_discover=True,
    discover_patterns=["controllers", "services", "models", "middleware", "guards"],
)


__all__ = ["manifest"]