import { useTheme } from '../../../context/ThemeContext'
import { CodeBlock } from '../../../components/CodeBlock'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, ShieldCheck } from 'lucide-react'
import { NextSteps } from '../../../components/NextSteps'

export function SigningOverview() {
  const { theme } = useTheme()
  const isDark = theme === 'dark'
  const textMuted = isDark ? 'text-gray-400' : 'text-gray-600'
  const borderMuted = isDark ? 'border-white/5' : 'border-gray-100'

  return (
    <div className="max-w-4xl mx-auto py-6 font-sans">
      {/* Header */}
      <div className="mb-12">
        <div className="flex items-center gap-2 text-sm text-aquilia-500 font-mono mb-4">
          <ShieldCheck className="w-4 h-4" />
          <span>SIGNING SYSTEM / OVERVIEW</span>
        </div>
        <h1 className={`text-4xl font-light tracking-tight mb-4 ${isDark ? 'text-white' : 'text-gray-900'}`}>
          Cryptographic Signing Overview
        </h1>
        <p className={`text-lg leading-relaxed font-light ${textMuted}`}>
          Secure data payload transit across untrusted environments. Learn about Aquilia's zero-dependency, OWASP-aligned cryptographic signing subsystem.
        </p>
      </div>

      {/* Design Principles */}
      <section className="mb-16">
        <h2 className="text-xl font-mono text-aquilia-400 uppercase tracking-wider mb-6">Core Design Principles</h2>
        <div className={`space-y-6 font-light leading-relaxed ${textMuted}`}>
          <p>
            The signing subsystem allows Aquilia applications to delegate state storage to clients (in cookies, tokens, or URL query parameters) without risking payload tampering. It is designed around the following architectural guidelines:
          </p>
          <div className="border-l-2 border-aquilia-500/20 pl-6 space-y-4 py-1">
            <p>
              <strong className="font-semibold text-aquilia-500">Zero Mandatory Dependencies:</strong> By default, all HMAC implementations use Python's standard library (e.g. <code className="text-white">hmac</code>, <code className="text-white">hashlib</code>).
            </p>
            <p>
              <strong className="font-semibold text-aquilia-500">Namespace Isolation (Salting):</strong> Using salt values mixes namespaces into derived sub-keys, rendering signatures generated by different signers incompatible even when sharing the same master key.
            </p>
            <p>
              <strong className="font-semibold text-aquilia-500">Constant-Time Comparisons:</strong> Signature validation utilizes <code className="text-white">hmac.compare_digest</code> to protect against side-channel timing attacks.
            </p>
            <p>
              <strong className="font-semibold text-aquilia-500">Algorithm Agility:</strong> Supports standard HMAC algorithms (HS256, HS384, HS512) and asymmetric signatures (RS256, ES256, EdDSA) via the optional <code className="text-white">cryptography</code> package.
            </p>
          </div>
        </div>
      </section>

      {/* Fault Mappings */}
      <section className="mb-16">
        <h2 className="text-xl font-mono text-aquilia-400 uppercase tracking-wider mb-6">Signing Faults &amp; Exceptions</h2>
        <p className={`font-light leading-relaxed ${textMuted} mb-6`}>
          Aquilia maps its standard faults to legacy exceptions, keeping client-code integration straightforward:
        </p>

        <CodeBlock language="python" filename="signing_faults.py" compact showLineNumbers={false}>{`class SigningError(SigningFault):
    """Base exception for all signing-related operations."""

class BadSignature(BadSignatureFault):
    """Raised when signature verification fails."""

class SignatureExpired(SignatureExpiredFault):
    """Raised when signature validation succeeds but timestamp age exceeds max_age."""

class SignatureMalformed(SignatureMalformedFault):
    """Raised when the token format or encoding is corrupted."""

class UnsupportedAlgorithmError(UnsupportedAlgorithmFault):
    """Raised when an algorithm is selected but its dependencies are missing."""`}</CodeBlock>
      </section>

      {/* Low-Level Primitives */}
      <section className="mb-16">
        <h2 className="text-xl font-mono text-aquilia-400 uppercase tracking-wider mb-6">Low-Level Cryptographic Primitives</h2>
        <p className={`font-light leading-relaxed ${textMuted} mb-6`}>
          The module exposes pure utility functions for URL-safe base64 encoding and sub-key derivation:
        </p>

        <CodeBlock language="python" filename="signing_primitives.py" compact showLineNumbers={false}>{`def b64_encode(data: bytes) -> str:
    """URL-safe, no-padding Base64 encoder."""

def b64_decode(data: str | bytes) -> bytes:
    """URL-safe, no-padding Base64 decoder. Validates canonical encoding."""

def constant_time_compare(a: bytes | str, b: bytes | str) -> bool:
    """Compares strings in constant time to prevent timing attacks."""

def derive_key(secret: str | bytes, salt: str, algorithm: str = "HS256") -> bytes:
    """Derives a namespace-specific sub-key using HKDF-lite to prevent cross-confusion."""`}</CodeBlock>
      </section>

      {/* Navigation */}
      <div className={`flex items-center justify-between pt-8 mt-12 border-t ${borderMuted}`}>
        <Link to="/docs/sse/resources" className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors">
          <ArrowLeft className="w-4 h-4" /> Resource Management
        </Link>
        <Link to="/docs/signing/signers" className="flex items-center gap-2 text-sm text-aquilia-500 font-semibold hover:text-aquilia-400 transition-colors">
          Core Signers <ArrowRight className="w-4 h-4" />
        </Link>
      </div>

      <NextSteps />
    </div>
  )
}
