"""
Aquilia Workspace — myapp (minimal)
Generated by: aq init workspace myapp --minimal

Architecture:
- workspace.py = orchestration (which modules, integrations)
- modules/*/manifest.py = source of truth (controllers, services, middleware)
"""

from aquilia import Workspace, Module, Integration

workspace = (
    Workspace(
        name="myapp",
        version="0.1.0",
        description="myapp workspace",
    )

    # ---- Modules ---------------------------------------------------------
    # Each Module() is a pointer to its manifest.py.
    # Controllers, services, and middleware are declared in manifest.py,
    # NOT here. The workspace only sets orchestration metadata.

    .module(Module("products", version="0.1.0", description="Products module")
        .route_prefix("/products")
        .tags("products", "core"))

    .module(Module("auth", version="0.1.0", description="Auth module")
        .route_prefix("/auth"))

    .module(Module("users", version="0.1.0", description="Users module")
        .route_prefix("/users")
        .tags("users", "core"))

    # Integrations — core only
    .integrate(Integration.di(auto_wire=True))
    .integrate(Integration.routing(strict_matching=True))
    .integrate(Integration.fault_handling(default_strategy="propagate"))
    .integrate(Integration.patterns())
)

__all__ = ["workspace"]