"""
Aquilia Workspace Configuration - Production Grade
Generated by: aq init workspace myapp

This file defines the WORKSPACE STRUCTURE (modules, integrations).
It is:
- Environment-agnostic
- Version-controlled and shared across team
- Type-safe with full IDE support
- Observable via introspection

Runtime settings (host, port, workers) come from config/dev.yaml or config/prod.yaml.

Separation of concerns:
- aquilia.py (THIS FILE) = Workspace structure (modules, integrations)
- config/base.yaml = Shared configuration defaults
- config/{mode}.yaml = Environment-specific runtime settings (dev, prod)
- Environment variables = Override mechanism for secrets and env-specific values
"""

from aquilia import Workspace, Module, Integration, SessionPolicy
from datetime import timedelta
from aquilia.sessions import TransportPolicy

# Define workspace structure
workspace = (
    Workspace(
        name="myapp",
        version="0.1.0",
        description="Aquilia workspace",
    )
    # Starter module — registered here so the server does not need
    # to hard-code it. Delete this line (and starter.py) once you
    # add your own modules with a GET "/" route.
    .starter("starter")

    # Add modules here with explicit configuration:
    # .module(Module("auth", version="1.0.0", description="Authentication module").route_prefix("/api/v1/auth").depends_on("core"))
    # .module(Module("users", version="1.0.0", description="User management").route_prefix("/api/v1/users").depends_on("auth", "core"))

    # ---- Modules ---------------------------------------------------------

    .module(Module("authentication", version="0.1.0", description="Authentication module")
        .route_prefix("/authentication")
        .tags("authentication"))

    # Integrations - Configure core systems
    .integrate(Integration.di(auto_wire=True, manifest_validation=True))
    .integrate(Integration.registry(
        mode="auto",  # "dev", "prod", "auto" (env-based)
        fingerprint_verification=True,
    ))
    .integrate(Integration.routing(
        strict_matching=True,
        version_support=True,
        compression=True,
    ))
    .integrate(Integration.fault_handling(
        default_strategy="propagate",
        metrics_enabled=True,
    ))
    .integrate(Integration.patterns())

    # Database - Configure the ORM backend
    # Uncomment and set the connection URL for your database.
    .integrate(Integration.database(
        # url="sqlite:///db.sqlite3",     # SQLite (dev)
        # url="postgresql://user:pass@localhost:5432/myapp",  # PostgreSQL
        pool_size=5,
        echo=False,
        auto_migrate=False,
    ))

    # Cache - In-memory by default, switch to Redis for production
    .integrate(Integration.cache(
        backend="memory",
        default_ttl=300,
        max_size=1024,
        key_prefix="myapp:",
    ))

    # Templates - Fluent configuration
    .integrate(
        Integration.templates
        .source("templates")
        .scan_modules()
        .cached("memory")
        .secure()
    )

    # Static Files - Serve static assets (CSS, JS, images)
    .integrate(Integration.static_files(
        directories={"/static": "static"},
        cache_max_age=86400,
        etag=True,
    ))

    # Sessions (uncomment to enable session management)
    .sessions(
        policies=[
            SessionPolicy(
                name="default",
                ttl=timedelta(days=7),
                idle_timeout=timedelta(hours=1),
            ),
        ],
    )

    # Security (uncomment to enable security middleware)
    # Fine-grained: use Integration.cors(), Integration.csp(),
    # Integration.rate_limit() with .integrate().
    # .security(
    #     cors_enabled=False,
    #     csrf_protection=False,
    #     helmet_enabled=True,
    #     rate_limiting=False,
    # )

    # Telemetry (uncomment to enable observability)
    # .telemetry(
    #     tracing_enabled=False,
    #     metrics_enabled=True,
    #     logging_enabled=True,
    # )

    # Admin Dashboard (uncomment to enable admin at /admin/)
    # Requires: aq admin createsuperuser
    .integrate(Integration.admin(
        url_prefix="/admin",
        site_title="myapp Admin",
        auto_discover=True,
    ))

    .integrate(
        Integration.database(
            url = "sqlite:///db.sqlite3"
        )
    )
)

# Export for CLI/server
__all__ = ["workspace"]