"""
CI/CD templates and GitHub Actions configuration.

Generates:
- ``.github/workflows/aquilia-ci.yml`` -- build, test, publish, deploy
- Dockerfile for reproducible builds
"""

from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger("aquilia.mlops.release.ci")


GITHUB_ACTIONS_WORKFLOW = """\
# Aquilia MLOps CI/CD Pipeline
# Auto-generated by: aq ci generate

name: Aquilia Model CI/CD

on:
  push:
    branches: [main, master]
    paths:
      - 'models/**'
      - 'manifest.json'
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-modelpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
          pip install aquilia

      - name: Validate manifest
        run: aq validate

      - name: Run model unit tests
        run: pytest tests/ -v --tb=short

      - name: Build modelpack
        run: aq pack save --name ${{ github.event.repository.name }} --version v${{ github.run_number }}

      - name: Smoke test (local serve)
        run: |
          aq serve --model *.aquilia --timeout 30 --smoke-test

      - name: Upload modelpack artifact
        uses: actions/upload-artifact@v4
        with:
          name: modelpack
          path: '*.aquilia'

  publish:
    needs: build-modelpack
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: modelpack

      - name: Publish to registry
        run: |
          aq pack push *.aquilia \\
            --registry ${{ secrets.AQUILIA_REGISTRY_URL }} \\
            --token ${{ secrets.AQUILIA_REGISTRY_TOKEN }}

  deploy-staging:
    needs: publish
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          aq deploy \\
            registry://${{ github.event.repository.name }}:latest \\
            --to k8s \\
            --namespace staging \\
            --replicas 1
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
"""

DOCKERFILE_TEMPLATE = """\
# Aquilia Model Serving Container
# Auto-generated by: aq ci generate

FROM python:3.11-slim AS base

WORKDIR /app

# Install system deps
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Install Python deps
COPY requirements.txt env.lock* ./
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || true
RUN pip install --no-cache-dir aquilia

# Copy model artifacts
COPY *.aquilia ./
RUN aq pack inspect *.aquilia

# Expose serving port
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\
    CMD curl -f http://localhost:8080/health || exit 1

# Run model server
CMD ["aq", "serve", "--bind", "0.0.0.0:8080"]

LABEL org.opencontainers.image.source="aquilia-mlops"
"""


def generate_ci_workflow(output_dir: str = ".github/workflows") -> str:
    """Generate GitHub Actions workflow file."""
    from pathlib import Path
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "aquilia-ci.yml"
    path.write_text(GITHUB_ACTIONS_WORKFLOW, encoding="utf-8")
    return str(path)


def generate_dockerfile(output_dir: str = ".") -> str:
    """Generate Dockerfile for model serving."""
    from pathlib import Path
    path = Path(output_dir) / "Dockerfile.aquilia"
    path.write_text(DOCKERFILE_TEMPLATE, encoding="utf-8")
    return str(path)
