"""
Aquilia Workspace Configuration - Production Grade
Generated by: aq init workspace authentication

This file defines the WORKSPACE STRUCTURE (modules, integrations).
It is:
- Environment-agnostic
- Version-controlled and shared across team
- Type-safe with full IDE support
- Observable via introspection

Runtime settings (host, port, workers) come from config/dev.yaml or config/prod.yaml.

Separation of concerns:
- aquilia.py (THIS FILE) = Workspace structure (modules, integrations)
- config/base.yaml = Shared configuration defaults
- config/{mode}.yaml = Environment-specific runtime settings (dev, prod)
- Environment variables = Override mechanism for secrets and env-specific values
"""

from aquilia import Workspace, Module, Integration
from datetime import timedelta
from aquilia.sessions import SessionPolicy, PersistencePolicy, ConcurrencyPolicy, TransportPolicy

# Define workspace structure
workspace = (
    Workspace(
        name="authentication",
        version="0.1.0",
        description="Aquilia workspace",
    )
    # Starter — the server auto-loads starter.py from the workspace
    # root when debug=True. No need to register it as a module.
    # Delete starter.py once you add your own routes.

    # Add modules here with explicit configuration:
    # .module(Module("auth", version="1.0.0", description="Authentication module").route_prefix("/api/v1/auth").depends_on("core"))
    # .module(Module("users", version="1.0.0", description="User management").route_prefix("/api/v1/users").depends_on("auth", "core"))

    # ---- Modules ---------------------------------------------------------

    .module(Module("auth", version="0.1.0", description="Auth module")
        .route_prefix("/auth")
        .tags("auth", "core")
        .register_controllers(
            "modules.auth.controllers:AuthController"
        )
        .register_services(
            "modules.auth.services:AuthService"
        ))

    .module(Module("dashboard", version="0.1.0", description="Dashboard module")
        .route_prefix("/dashboard")
        .tags("dashboard", "core")
        .register_controllers(
            "modules.dashboard.controllers:DashboardController"
        )
        .register_services(
            "modules.dashboard.services:DashboardService"
        ))

    # Integrations - Configure core systems
    .integrate(Integration.di(auto_wire=True, manifest_validation=True))
    .integrate(Integration.registry(
        mode="auto",  # "dev", "prod", "auto" (env-based)
        fingerprint_verification=True,
    ))
    .integrate(Integration.routing(
        strict_matching=True,
        version_support=True,
        compression=True,
    ))
    .integrate(Integration.fault_handling(
        default_strategy="propagate",
        metrics_enabled=True,
    ))
    .integrate(Integration.patterns())

    # Templates - Fluent configuration
    .integrate(
        Integration.templates
        .source("templates")
        .scan_modules()
        .cached("memory")
        .secure()
    )

    # Static Files - Serve static assets (CSS, JS, images)
    .integrate(Integration.static_files(
        directories={
            "/static": "static",
            "/uploads": "authentication/uploads"
        },
        cache_max_age=86400,
        etag=True,
    ))

    # Sessions - Configure session management
    .sessions(
        policies=[
            # Default session policy for web users
            SessionPolicy(
                name="default",
                ttl=timedelta(days=7),
                idle_timeout=timedelta(hours=1),
                rotate_on_privilege_change=True,
                persistence=PersistencePolicy(
                    enabled=True,
                    store_name="memory",
                    write_through=True,
                ),
                concurrency=ConcurrencyPolicy(
                    max_sessions_per_principal=5,
                    behavior_on_limit="evict_oldest",
                ),
                transport=TransportPolicy(
                    adapter="cookie",
                    cookie_httponly=True,
                    cookie_secure=False,  # Set to True in production
                    cookie_samesite="lax",
                ),
                scope="user",
            ),
        ],
    )

    # Security - Enable/disable security features
    # These flags control which security middleware are auto-registered.
    # For fine-grained control, use Integration.cors(), Integration.csp(),
    # Integration.rate_limit() with .integrate().
    .security(
        cors_enabled=False,       # Enable CORS (configure with Integration.cors() for details)
        csrf_protection=False,    # Enable CSRF protection tokens
        helmet_enabled=True,      # Enable Helmet-style security headers (X-Frame-Options, etc.)
        rate_limiting=True,       # Enable rate limiting (100 req/min default)
        https_redirect=False,     # Enable HTTP→HTTPS redirect (enable in production)
        hsts=False,               # Enable HSTS header (enable in production)
        proxy_fix=False,          # Enable X-Forwarded-* processing (enable behind reverse proxy)
    )

    # Telemetry - Enable observability
    .telemetry(
        tracing_enabled=False,
        metrics_enabled=True,
        logging_enabled=True,
    )

    .integrate(Integration.database(
        url = "sqlite:///db.sqlite"
    ))
)

# Export for CLI/server
__all__ = ["workspace"]